require('dotenv').config();

const energyTokenContract = require('./contracts/EnergyToken').default;

const {
  REACT_APP_CONTRACT_ADDRESS,
  REACT_APP_ETHEREUM_PASSWORD,
  REACT_APP_ETHEREUM_PROVIDER_IP,
  REACT_APP_BACKEND_URL,
  REACT_APP_ENERGY_TOKEN_CONTRACT_OWNER,
} = process.env;

if (!REACT_APP_ETHEREUM_PASSWORD) {
  console.log('[WARNING] ETHEREUM_PASSWORD is empty')
}

if (!REACT_APP_CONTRACT_ADDRESS) {
  console.log('[WARNING] ENERGY_TOKEN_CONTRACT_ADDRESS is empty');
}

if (!REACT_APP_ETHEREUM_PROVIDER_IP) {
  console.log('[WARNING] ETHEREUM_PROVIDER_IP is empty');
}

if (!REACT_APP_BACKEND_URL) {
  console.log('[WARNING] REACT_APP_BACKEND_URL is empty');
}

if (!REACT_APP_ENERGY_TOKEN_CONTRACT_OWNER) {
  console.log('[WARNING] REACT_APP_ENERGY_TOKEN_CONTRACT_OWNER is empty');
}

const YOUR_ETH_NODE_ADDRESS = REACT_APP_ETHEREUM_PROVIDER_IP;

const YOUR_ENERGY_TOKEN_CONTRACT_ADDRESS = REACT_APP_CONTRACT_ADDRESS;
const YOUR_ENERGY_TOKEN_CONTRACT_ADDRESS_ABI = energyTokenContract(REACT_APP_CONTRACT_ADDRESS);

const ETHEREUM_PASSWORD = REACT_APP_ETHEREUM_PASSWORD;
const BACKEND_URL = REACT_APP_BACKEND_URL || 'http://localhost:3030/';
const YOUR_ENERGY_TOKEN_CONTRACT_OWNER = REACT_APP_ENERGY_TOKEN_CONTRACT_OWNER;

export default {
  YOUR_ETH_NODE_ADDRESS,
  YOUR_ENERGY_TOKEN_CONTRACT_ADDRESS,
  YOUR_ENERGY_TOKEN_CONTRACT_ADDRESS_ABI,
  ETHEREUM_PASSWORD,
  BACKEND_URL,
  YOUR_ENERGY_TOKEN_CONTRACT_OWNER
};
