# Use postgres/example user/password credential
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
        - POSTGRES_PASSWORD=test_pw
        - POSTGRES_DB=energytoken
        - POSTGRES_USER=test_user
      
    ports: 
        - '5432:5432'
    
    volumes:
        - ./pgdata:/var/lib/postgresql/data